"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""

def fib2(n): # return Fibonacci series up to n
	"""Return a list containing the Fibonacci series up to n"""
	temp = 0
	a, b = 0, 1
	while b < n:
		a, b = b, a + b
		if b % 2 == 0:
			temp += b
	return temp

print fib2(4000000)